// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCBs5oTLTbnMWu_l_-jMBRHI6XnCHLC8k',
    appId: '1:312711245712:web:5c8ce6cc4bef7a4fd18d15',
    messagingSenderId: '312711245712',
    projectId: 'flutterpost-7d168',
    authDomain: 'flutterpost-7d168.firebaseapp.com',
    storageBucket: 'flutterpost-7d168.firebasestorage.app',
    measurementId: 'G-FY6ZZQY443',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeTec6k3-msSM7ZFdoOd9j4OgmV0M4bbE',
    appId: '1:312711245712:android:9e059ca131f42ab9d18d15',
    messagingSenderId: '312711245712',
    projectId: 'flutterpost-7d168',
    storageBucket: 'flutterpost-7d168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrmjGjd2oWfxtMkkdlTx8B_nvy-jGX5C8',
    appId: '1:312711245712:ios:65c42e63f6f0a333d18d15',
    messagingSenderId: '312711245712',
    projectId: 'flutterpost-7d168',
    storageBucket: 'flutterpost-7d168.firebasestorage.app',
    iosBundleId: 'com.example.flutterPost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrmjGjd2oWfxtMkkdlTx8B_nvy-jGX5C8',
    appId: '1:312711245712:ios:65c42e63f6f0a333d18d15',
    messagingSenderId: '312711245712',
    projectId: 'flutterpost-7d168',
    storageBucket: 'flutterpost-7d168.firebasestorage.app',
    iosBundleId: 'com.example.flutterPost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCBs5oTLTbnMWu_l_-jMBRHI6XnCHLC8k',
    appId: '1:312711245712:web:8af72e8e8d8a1717d18d15',
    messagingSenderId: '312711245712',
    projectId: 'flutterpost-7d168',
    authDomain: 'flutterpost-7d168.firebaseapp.com',
    storageBucket: 'flutterpost-7d168.firebasestorage.app',
    measurementId: 'G-MEQ0LG8NL0',
  );
}
